### ISSUE TITLE
`rgb.txt` deleted upstream

### ISSUE THREAD

**Issue by ctrlcctrlv** [ofavre/vimcat#13]
https://github.com/ctrlcctrlv/rgb.txt is a temporary solution to this.

I wish @brammool will restore the file.

**Comment by ctrlcctrlv** [comment]
Humorously vimcat needs neither version, though will work w/2004 one.

It needs https://raw.githubusercontent.com/ctrlcctrlv/rgb.txt/master/rgb.txt .

**Comment by ofavre** [comment]
I see that it's been replaced with [`./runtime/colors/lists/default.vim`](https://github.com/vim/vim/blob/master/runtime/colors/lists/default.vim).
I'll give it a try as it seems more sustainable, and closer to the actual output `vim` would give if a user has tweaked those colors.

**Comment by ctrlcctrlv** [comment]
neato, i didn't notice that file. well, i have a working AUR PKGBUILD using my rgb.txt restoration, but if you want to be closer to mainline vim that's welcome.

https://aur.archlinux.org/packages/vimcat

**Comment by ctrlcctrlv** [comment]
i really like this software, use it a lot, it's very useful piped through `ansifilter -H -f` or `aha`. `vim` can highlight a lot of languages nothing else can touch, and it's such a natural solution to the problem. also you can pass `set nu` on the fly, it's a very smart solution to the problem pygmentize etc. tries to solve w/o the benefit of a super active community developing syntax files.

**Comment by ctrlcctrlv** [comment]
i really like this software, use it a lot, it's very useful piped through `ansifilter -H -f` or `aha`. `vim` can highlight a lot of languages nothing else can touch, and it's such a natural solution to the problem. also you can pass `set nu` on the fly, it's a very smart solution to the problem pygmentize etc. tries to solve w/o the benefit of a super active community developing syntax files.

**Comment by ofavre** [comment]
Thank you for the kind words, much appreciated.
It's a strange feeling to have a weird idea, put in the time to make it a reality, open source it (even if it's just to store it somewhere only I will go back to later), coming back to it a decade later to finally have it run in an acceptable speed, and discovering a few dozen people starred it and find value in it, sometimes opening tickets on other repositories so that both tools play better together. ☺️
